import { ComponentCapability } from '../types';

export const buttonCapability: ComponentCapability = {
  id: 'button',
  name: 'Button',
  displayName: 'Button',
  category: 'Actions',
  description: 'Interactive pressable action trigger with variant hierarchy, sizing scale, loading indicators, and platform-native touch standards.',
  slots: [
    { name: 'leading-icon', description: 'Vector icon displayed before button label', platforms: ['web', 'android', 'ios', 'windows', 'macos'] },
    { name: 'trailing-icon', description: 'Vector icon displayed after button label', platforms: ['web', 'android', 'ios', 'windows', 'macos'] },
    { name: 'loading-indicator', description: 'Progress spinner shown when loading is active', platforms: ['web', 'android', 'ios', 'windows', 'macos'] },
    { name: 'label', description: 'Primary action text', platforms: ['web', 'android', 'ios', 'windows', 'macos'] },
  ],
  recipes: [
    { id: 'basic', title: 'Action Hierarchy', description: 'Primary, secondary, outline, ghost, and danger variants.', platforms: ['web', 'android', 'ios', 'windows', 'macos'] },
    { id: 'loading', title: 'Async Loading Action', description: 'Button with disabled state and non-blocking spinner indicator.', platforms: ['web', 'android', 'ios', 'windows', 'macos'] },
    { id: 'icon-action', title: 'Button with Leading / Trailing Icon', description: 'Standard button paired with authentic SVG icon.', platforms: ['web', 'android', 'ios', 'windows', 'macos'] },
    { id: 'destructive', title: 'Destructive Confirmation Action', description: 'High-contrast red danger button for irrevocable actions.', platforms: ['web', 'android', 'ios', 'windows', 'macos'] },
    { id: 'split-action', title: 'Split Button with Dropdown', description: 'Dual-action trigger combining primary execute and menu expand.', platforms: ['web', 'windows', 'macos'] },
  ],
  bestPractices: {
    do: [
      'Use only one primary action button per screen section or dialog',
      'Provide visible keyboard focus outlines on desktop web and windows',
      'Respect 48dp minimum touch target on Android and 44pt on iOS',
    ],
    dont: [
      'Never use generic emoji characters for button icons; use @winplaybox/icons',
      'Never remove keyboard focus outlines without providing accessible alternatives',
    ],
  },
  platforms: {
    web: {
      platform: 'web',
      support: 'native',
      implementation: '@winplaybox/react',
      variants: ['primary', 'secondary', 'outline', 'ghost', 'danger'],
      recipes: ['basic', 'loading', 'icon-action', 'destructive', 'split-action'],
      states: ['default', 'hover', 'focus', 'active', 'disabled', 'loading'],
      interactions: ['mouse-click', 'keyboard-enter', 'keyboard-space'],
      accessibility: ['role="button"', 'tabindex="0"', 'aria-disabled', 'aria-busy'],
      testStatus: 'verified',
    },
    android: {
      platform: 'android',
      support: 'native',
      implementation: '@winplaybox/react-native',
      variants: ['primary', 'secondary', 'outline', 'ghost', 'danger'],
      recipes: ['basic', 'loading', 'icon-action', 'destructive'],
      states: ['default', 'pressed', 'disabled', 'loading'],
      interactions: ['touch-tap', 'android-ripple', 'elevation-lift'],
      accessibility: ['accessibilityRole="button"', '48dp touch target'],
      testStatus: 'verified',
    },
    ios: {
      platform: 'ios',
      support: 'native',
      implementation: '@winplaybox/react-native',
      variants: ['primary', 'secondary', 'outline', 'ghost', 'danger'],
      recipes: ['basic', 'loading', 'icon-action', 'destructive'],
      states: ['default', 'pressed', 'disabled', 'loading'],
      interactions: ['touch-tap', 'haptic-feedback', 'opacity-fade'],
      accessibility: ['accessibilityRole="button"', 'accessibilityTraits=["button"]', '44pt touch target'],
      testStatus: 'verified',
    },
    windows: {
      platform: 'windows',
      support: 'adapted',
      implementation: '@winplaybox/react-native-windows',
      variants: ['primary', 'subtle', 'accent'],
      recipes: ['basic', 'loading', 'icon-action'],
      states: ['default', 'hover', 'focus', 'pressed', 'disabled'],
      interactions: ['mouse-click', 'keyboard-space', 'tab-focus'],
      accessibility: ['UIAutomation Button pattern'],
      testStatus: 'verified',
    },
    macos: {
      platform: 'macos',
      support: 'adapted',
      implementation: '@winplaybox/react-native-macos',
      variants: ['primary', 'inline', 'bordered'],
      recipes: ['basic', 'loading', 'icon-action'],
      states: ['default', 'hover', 'pressed', 'disabled'],
      interactions: ['mouse-click', 'trackpad-tap', 'return-key'],
      accessibility: ['NSAccessibilityButtonRole'],
      testStatus: 'verified',
    },
  },
};
