import { ComponentCapability } from '../types';

export const cardCapability: ComponentCapability = {
  id: 'card',
  name: 'Card',
  displayName: 'Card',
  category: 'Surfaces',
  description: 'Contained surface container for grouping related content, actions, and media across tokenized elevations.',
  slots: [
    { name: 'header', description: 'Title, subtitle, and action buttons', platforms: ['web', 'android', 'ios', 'windows', 'macos'] },
    { name: 'body', description: 'Primary card content and layout', platforms: ['web', 'android', 'ios', 'windows', 'macos'] },
    { name: 'footer', description: 'Action triggers, confirmations, or metadata', platforms: ['web', 'android', 'ios', 'windows', 'macos'] },
    { name: 'media', description: 'Cover image or illustration header', platforms: ['web', 'android', 'ios', 'windows', 'macos'] },
  ],
  recipes: [
    { id: 'standard', title: 'Content Card with Actions', description: 'Elevated card surface with header, body copy, and trailing buttons.', platforms: ['web', 'android', 'ios', 'windows', 'macos'] },
    { id: 'interactive', title: 'Clickable Card Tile', description: 'Card behaving as a unified interactive surface with hover and press response.', platforms: ['web', 'android', 'ios', 'windows', 'macos'] },
    { id: 'outlined', title: 'Flat Outlined Card', description: 'Zero-elevation card with subtle 1px border for clean dashboards.', platforms: ['web', 'android', 'ios', 'windows', 'macos'] },
  ],
  bestPractices: {
    do: [
      'Use semantic surface tokens var(--color-surface) and var(--color-surface-raised)',
      'For interactive cards, provide an accessible name for the entire container',
    ],
    dont: [
      'Never nest multiple interactive focus stops directly inside a single interactive card button container',
    ],
  },
  platforms: {
    web: {
      platform: 'web',
      support: 'native',
      implementation: '@winplaybox/react',
      variants: ['elevated', 'outlined', 'flat'],
      recipes: ['standard', 'interactive', 'outlined'],
      states: ['default', 'hover', 'focus'],
      interactions: ['hover-lift', 'click'],
      accessibility: ['role="region" or role="article"', 'aria-labelledby'],
      testStatus: 'verified',
    },
    android: {
      platform: 'android',
      support: 'native',
      implementation: '@winplaybox/react-native',
      variants: ['elevated', 'outlined', 'flat'],
      recipes: ['standard', 'interactive', 'outlined'],
      states: ['default', 'pressed'],
      interactions: ['touch', 'native-elevation-shadow', 'ripple'],
      accessibility: ['accessibilityRole="none" or "button"'],
      testStatus: 'verified',
    },
    ios: {
      platform: 'ios',
      support: 'native',
      implementation: '@winplaybox/react-native',
      variants: ['elevated', 'outlined', 'flat'],
      recipes: ['standard', 'interactive', 'outlined'],
      states: ['default', 'pressed'],
      interactions: ['touch', 'ios-shadow-path', 'opacity-feedback'],
      accessibility: ['accessibilityRole="none" or "button"'],
      testStatus: 'verified',
    },
    windows: {
      platform: 'windows',
      support: 'adapted',
      implementation: '@winplaybox/react-native-windows',
      variants: ['elevated', 'outlined', 'flat'],
      recipes: ['standard', 'interactive', 'outlined'],
      states: ['default', 'hover'],
      interactions: ['mouse-hover', 'keyboard-focus'],
      accessibility: ['UIAutomation Group control'],
      testStatus: 'verified',
    },
    macos: {
      platform: 'macos',
      support: 'adapted',
      implementation: '@winplaybox/react-native-macos',
      variants: ['elevated', 'outlined', 'flat'],
      recipes: ['standard', 'interactive', 'outlined'],
      states: ['default', 'hover'],
      interactions: ['trackpad-hover', 'click'],
      accessibility: ['NSAccessibilityGroupRole'],
      testStatus: 'verified',
    },
  },
};
