import { ComponentCapability } from '../types';

export const copyButtonCapability: ComponentCapability = {
  id: 'copy-button',
  name: 'CopyButton',
  displayName: 'Copy Button',
  category: 'Inputs',
  description: 'Clipboard action button with feedback animation, timeout reset, and zero-emoji authentic vector icons.',
  slots: [
    { name: 'leading-icon', description: 'Resting clipboard vector icon', platforms: ['web', 'android', 'ios', 'windows', 'macos'] },
    { name: 'success-icon', description: 'Success checkmark feedback vector icon', platforms: ['web', 'android', 'ios', 'windows', 'macos'] },
    { name: 'label', description: 'Text label for resting and copied feedback', platforms: ['web', 'android', 'ios', 'windows', 'macos'] },
  ],
  recipes: [
    {
      id: 'basic',
      title: 'Action Variants & Label Feedback',
      description: 'Standard button triggering system clipboard copy with animated label transition and 2s timeout.',
      platforms: ['web', 'android', 'ios', 'windows', 'macos'],
    },
    {
      id: 'compact-icon',
      title: 'Icon-Only Compact Mode & Tooltip',
      description: 'Square compact copy button ideal for code blocks, URLs, and token hashes.',
      platforms: ['web', 'android', 'ios', 'windows', 'macos'],
    },
    {
      id: 'custom-labels',
      title: 'Custom Resting & Copied Labels',
      description: 'Context-specific feedback strings (e.g. "Copy Contract Hash" -> "Hash Copied!").',
      platforms: ['web', 'android', 'ios', 'windows', 'macos'],
    },
  ],
  bestPractices: {
    do: [
      'Provide clear accessible labels for screen readers when using iconOnly mode',
      'Keep feedback timeout between 1500ms and 2500ms for optimal user awareness',
      'Use haptic feedback on touch platforms (iOS & Android) when clipboard write succeeds',
    ],
    dont: [
      'Never use emoji characters (e.g. 📋, 📋✅) for copy feedback; use authentic @winplaybox/icons',
      'Never trigger destructive side effects alongside clipboard copy actions',
    ],
  },
  platforms: {
    web: {
      platform: 'web',
      support: 'native',
      implementation: '@winplaybox/react',
      variants: ['primary', 'secondary', 'outline', 'ghost'],
      recipes: ['basic', 'compact-icon', 'custom-labels'],
      states: ['default', 'hover', 'focus', 'active', 'copied', 'disabled'],
      interactions: ['click', 'keyboard-enter', 'keyboard-space'],
      accessibility: ['aria-live="polite"', 'aria-label', 'keyboard-focus'],
      testStatus: 'verified',
    },
    android: {
      platform: 'android',
      support: 'native',
      implementation: '@winplaybox/react-native',
      variants: ['primary', 'secondary', 'outline', 'ghost'],
      recipes: ['basic', 'compact-icon', 'custom-labels'],
      states: ['default', 'pressed', 'copied', 'disabled'],
      interactions: ['touch-tap', 'android-ripple'],
      accessibility: ['accessibilityRole="button"', 'accessibilityLiveRegion="polite"', '48dp touch target'],
      testStatus: 'verified',
    },
    ios: {
      platform: 'ios',
      support: 'native',
      implementation: '@winplaybox/react-native',
      variants: ['primary', 'secondary', 'outline', 'ghost'],
      recipes: ['basic', 'compact-icon', 'custom-labels'],
      states: ['default', 'pressed', 'copied', 'disabled'],
      interactions: ['touch-tap', 'haptic-notification'],
      accessibility: ['accessibilityRole="button"', 'accessibilityTraits=["button"]', '44pt touch target'],
      testStatus: 'verified',
    },
    windows: {
      platform: 'windows',
      support: 'adapted',
      implementation: '@winplaybox/react-native-windows',
      variants: ['primary', 'subtle'],
      recipes: ['basic', 'compact-icon'],
      states: ['default', 'hover', 'focus', 'pressed', 'copied', 'disabled'],
      interactions: ['mouse-click', 'keyboard-space', 'accelerator-shortcut'],
      accessibility: ['UIAutomation Button pattern', 'focus-visuals'],
      testStatus: 'verified',
    },
    macos: {
      platform: 'macos',
      support: 'adapted',
      implementation: '@winplaybox/react-native-macos',
      variants: ['primary', 'inline'],
      recipes: ['basic', 'compact-icon'],
      states: ['default', 'hover', 'pressed', 'copied', 'disabled'],
      interactions: ['mouse-click', 'trackpad-tap', 'keyboard-space'],
      accessibility: ['NSAccessibilityButtonRole', 'voiceover-announcement'],
      testStatus: 'verified',
    },
  },
};
