import { ComponentCapability } from '../types';

export const dialogCapability: ComponentCapability = {
  id: 'dialog',
  name: 'Dialog',
  displayName: 'Dialog',
  category: 'Surfaces',
  description: 'Modal surface overlay for urgent user feedback, confirmations, and focused sub-workflows.',
  slots: [
    { name: 'header', description: 'Dialog title and close trigger', platforms: ['web', 'android', 'ios', 'windows', 'macos'] },
    { name: 'body', description: 'Modal content description or form inputs', platforms: ['web', 'android', 'ios', 'windows', 'macos'] },
    { name: 'footer', description: 'Action button row (Confirm / Cancel)', platforms: ['web', 'android', 'ios', 'windows', 'macos'] },
  ],
  recipes: [
    { id: 'confirmation', title: 'Confirmation Dialog', description: 'Explicit confirm and cancel action modal.', platforms: ['web', 'android', 'ios', 'windows', 'macos'] },
    { id: 'destructive', title: 'Destructive Warning Dialog', description: 'Irreversible action warning with red confirm button.', platforms: ['web', 'android', 'ios', 'windows', 'macos'] },
    { id: 'form-modal', title: 'Interactive Form Dialog', description: 'Contained inputs inside modal with submit handling.', platforms: ['web', 'windows', 'macos'] },
    { id: 'bottom-sheet', title: 'Mobile Bottom Sheet Dialog', description: 'Touch-friendly sheet anchored to bottom of mobile viewport.', platforms: ['android', 'ios'] },
  ],
  bestPractices: {
    do: [
      'Trap keyboard focus inside the dialog while open on Web and Desktop',
      'Provide an explicit close button with accessible aria-label or BackHandler on Android',
      'Restore focus to the opening trigger when the dialog closes',
    ],
    dont: [
      'Never open modals without user-initiated context or warning',
      'Never stack more than 2 modals on top of each other',
    ],
  },
  platforms: {
    web: {
      platform: 'web',
      support: 'native',
      implementation: '@winplaybox/react',
      variants: ['default', 'alert', 'fullscreen'],
      recipes: ['confirmation', 'destructive', 'form-modal'],
      states: ['closed', 'opening', 'open', 'closing'],
      interactions: ['backdrop-click', 'escape-key-close', 'tab-focus-trap'],
      accessibility: ['role="dialog"', 'aria-modal="true"', 'aria-labelledby'],
      testStatus: 'verified',
    },
    android: {
      platform: 'android',
      support: 'native',
      implementation: '@winplaybox/react-native',
      variants: ['default', 'alert'],
      recipes: ['confirmation', 'destructive', 'bottom-sheet'],
      states: ['closed', 'open'],
      interactions: ['back-button-close', 'touch-dismiss'],
      accessibility: ['accessibilityViewIsModal={true}'],
      testStatus: 'verified',
    },
    ios: {
      platform: 'ios',
      support: 'native',
      implementation: '@winplaybox/react-native',
      variants: ['default', 'alert'],
      recipes: ['confirmation', 'destructive', 'bottom-sheet'],
      states: ['closed', 'open'],
      interactions: ['swipe-down-dismiss', 'touch-dismiss'],
      accessibility: ['accessibilityViewIsModal={true}'],
      testStatus: 'verified',
    },
    windows: {
      platform: 'windows',
      support: 'adapted',
      implementation: '@winplaybox/react-native-windows',
      variants: ['default'],
      recipes: ['confirmation', 'destructive', 'form-modal'],
      states: ['closed', 'open'],
      interactions: ['escape-key', 'enter-confirm'],
      accessibility: ['UIAutomation Window pattern'],
      testStatus: 'verified',
    },
    macos: {
      platform: 'macos',
      support: 'adapted',
      implementation: '@winplaybox/react-native-macos',
      variants: ['default'],
      recipes: ['confirmation', 'destructive', 'form-modal'],
      states: ['closed', 'open'],
      interactions: ['escape-key', 'sheet-presentation'],
      accessibility: ['NSAccessibilitySheetRole'],
      testStatus: 'verified',
    },
  },
};
