import { ComponentCapability } from '../types';

export const iconButtonCapability: ComponentCapability = {
  id: 'icon-button',
  name: 'IconButton',
  displayName: 'Icon Button',
  category: 'Actions',
  description: 'Compact interactive vector icon button with mandatory accessibility label, visual press feedback, and minimum touch targets.',
  slots: [
    { name: 'icon', description: 'Vector SVG or native icon symbol', platforms: ['web', 'android', 'ios', 'windows', 'macos'] },
  ],
  recipes: [
    { id: 'standard', title: 'Toolbar Action Icon', description: 'Standard action trigger for toolbars, headers, and app bars.', platforms: ['web', 'android', 'ios', 'windows', 'macos'] },
    { id: 'subtle', title: 'Subtle Table Action', description: 'Low-contrast icon button that highlights on hover or press.', platforms: ['web', 'android', 'ios', 'windows', 'macos'] },
    { id: 'floating', title: 'Floating Action Trigger', description: 'Elevated circular action button with shadow.', platforms: ['android', 'ios', 'web'] },
  ],
  bestPractices: {
    do: [
      'Always supply an aria-label or accessibilityLabel for screen reader navigation',
      'Maintain 48x48dp touch bounds on Android and 44x44pt on iOS',
      'Use authentic vector icons centered with display: inline-flex',
    ],
    dont: [
      'Never render icon buttons without an accessible label',
      'Never use raster PNG or emoji characters inside icon buttons',
    ],
  },
  platforms: {
    web: {
      platform: 'web',
      support: 'native',
      implementation: '@winplaybox/react',
      variants: ['primary', 'secondary', 'subtle', 'danger'],
      recipes: ['standard', 'subtle', 'floating'],
      states: ['default', 'hover', 'focus', 'active', 'disabled', 'loading'],
      interactions: ['click', 'space-key', 'enter-key'],
      accessibility: ['aria-label', 'role="button"', 'focus-visible ring'],
      testStatus: 'verified',
    },
    android: {
      platform: 'android',
      support: 'native',
      implementation: '@winplaybox/react-native',
      variants: ['primary', 'secondary', 'subtle'],
      recipes: ['standard', 'subtle', 'floating'],
      states: ['default', 'pressed', 'disabled'],
      interactions: ['touch', 'native-ripple', '48dp-touch-target'],
      accessibility: ['accessibilityRole="button"', 'accessibilityLabel'],
      testStatus: 'verified',
    },
    ios: {
      platform: 'ios',
      support: 'native',
      implementation: '@winplaybox/react-native',
      variants: ['primary', 'secondary', 'subtle'],
      recipes: ['standard', 'subtle'],
      states: ['default', 'pressed', 'disabled'],
      interactions: ['touch', 'opacity-feedback', '44pt-touch-target'],
      accessibility: ['accessibilityRole="button"', 'accessibilityLabel'],
      testStatus: 'verified',
    },
    windows: {
      platform: 'windows',
      support: 'adapted',
      implementation: '@winplaybox/react-native-windows',
      variants: ['primary', 'secondary', 'subtle'],
      recipes: ['standard', 'subtle'],
      states: ['default', 'hover', 'focused', 'disabled'],
      interactions: ['mouse-click', 'keyboard-space-enter', 'tooltip-on-hover'],
      accessibility: ['UIAutomation Invoke pattern'],
      testStatus: 'verified',
    },
    macos: {
      platform: 'macos',
      support: 'adapted',
      implementation: '@winplaybox/react-native-macos',
      variants: ['primary', 'secondary', 'subtle'],
      recipes: ['standard', 'subtle'],
      states: ['default', 'hover', 'focused', 'disabled'],
      interactions: ['trackpad-click', 'keyboard-focus'],
      accessibility: ['NSAccessibilityButtonRole'],
      testStatus: 'verified',
    },
  },
};
