import { ComponentCapability } from '../types';

export const liveIndicatorCapability: ComponentCapability = {
  id: 'live-indicator',
  name: 'LiveIndicator',
  displayName: 'Live Indicator',
  category: 'Feedback',
  description: 'Subtle real-time status and broadcast indicator with pulse, beacon, and static variants, strictly respecting reduced-motion preferences.',
  slots: [
    { name: 'dot', description: 'Animated or static status orb/dot', platforms: ['web', 'android', 'ios', 'windows', 'macos'] },
    { name: 'label', description: 'Status text description (e.g. LIVE, RECORDING)', platforms: ['web', 'android', 'ios', 'windows', 'macos'] },
  ],
  recipes: [
    { id: 'pulse-live', title: 'Subtle Pulse Live Status', description: 'Default broadcast indicator with gentle CSS / Animated ripple pulse.', platforms: ['web', 'android', 'ios', 'windows', 'macos'] },
    { id: 'beacon-active', title: 'Concentric Beacon', description: 'Dual-ring radial pulse for mission-critical or active stream indicators.', platforms: ['web', 'android', 'ios', 'windows', 'macos'] },
    { id: 'static-recording', title: 'Static High-Contrast Pill', description: 'Calm, non-animating status beacon for accessibility or reduced-motion mode.', platforms: ['web', 'android', 'ios', 'windows', 'macos'] },
    { id: 'dot-only', title: 'Compact Dot-Only Beacon', description: 'Minimalist status indicator without text label for tight toolbars and table rows.', platforms: ['web', 'android', 'ios', 'windows', 'macos'] },
  ],
  bestPractices: {
    do: [
      'Always support prefers-reduced-motion / useReducedMotion by dampening or stopping the animation',
      'Use aria-live="polite" and role="status" so screen readers announce live state changes gracefully',
      'Keep animation subtle — avoid harsh neon blooms that distract users from primary tasks',
    ],
    dont: [
      'Never use flashing animations exceeding 3 flashes per second (WCAG 2.3.1)',
      'Never rely purely on color to communicate state; provide the accessible label',
    ],
  },
  platforms: {
    web: {
      platform: 'web',
      support: 'native',
      implementation: '@winplaybox/react',
      variants: ['pulse', 'beacon', 'static'],
      recipes: ['pulse-live', 'beacon-active', 'static-recording', 'dot-only'],
      states: ['default', 'hover'],
      interactions: ['css-keyframes-animation', 'reduced-motion-override'],
      accessibility: ['role="status"', 'aria-live="polite"', 'aria-label'],
      testStatus: 'verified',
    },
    android: {
      platform: 'android',
      support: 'native',
      implementation: '@winplaybox/react-native',
      variants: ['pulse', 'beacon', 'static'],
      recipes: ['pulse-live', 'beacon-active', 'static-recording', 'dot-only'],
      states: ['default'],
      interactions: ['Animated.loop', 'native-driver'],
      accessibility: ['accessibilityRole="image"', 'accessibilityLabel'],
      testStatus: 'verified',
    },
    ios: {
      platform: 'ios',
      support: 'native',
      implementation: '@winplaybox/react-native',
      variants: ['pulse', 'beacon', 'static'],
      recipes: ['pulse-live', 'beacon-active', 'static-recording', 'dot-only'],
      states: ['default'],
      interactions: ['Animated.loop', 'native-driver', 'UIAccessibilityIsReduceMotionEnabled'],
      accessibility: ['accessibilityLabel', 'VoiceOver live status readout'],
      testStatus: 'verified',
    },
    windows: {
      platform: 'windows',
      support: 'adapted',
      implementation: '@winplaybox/react-native-windows',
      variants: ['pulse', 'static'],
      recipes: ['pulse-live', 'static-recording', 'dot-only'],
      states: ['default'],
      interactions: ['Composition-animation', 'high-contrast-mode'],
      accessibility: ['UIAutomation LiveSetting.Polite'],
      testStatus: 'verified',
    },
    macos: {
      platform: 'macos',
      support: 'adapted',
      implementation: '@winplaybox/react-native-macos',
      variants: ['pulse', 'static'],
      recipes: ['pulse-live', 'static-recording', 'dot-only'],
      states: ['default'],
      interactions: ['CoreAnimation / Animated.loop'],
      accessibility: ['NSAccessibilityStatusRole'],
      testStatus: 'verified',
    },
  },
};
