import { ComponentCapability } from '../types';

export const textInputCapability: ComponentCapability = {
  id: 'text-input',
  name: 'TextInput',
  displayName: 'Text Input',
  category: 'Inputs',
  description: 'Foundational text entry control with validation states, leading/trailing slots, clear triggers, and cross-platform native contracts.',
  slots: [
    { name: 'leading-slot', description: 'Icon, prefix, or adornment at start of input', platforms: ['web', 'android', 'ios', 'windows', 'macos'] },
    { name: 'trailing-slot', description: 'Action button, password toggle, or clear trigger', platforms: ['web', 'android', 'ios', 'windows', 'macos'] },
    { name: 'label', description: 'Associated field title', platforms: ['web', 'android', 'ios', 'windows', 'macos'] },
    { name: 'helper-text', description: 'Supporting guidance or character count', platforms: ['web', 'android', 'ios', 'windows', 'macos'] },
    { name: 'error-message', description: 'Validation feedback announcement', platforms: ['web', 'android', 'ios', 'windows', 'macos'] },
  ],
  recipes: [
    { id: 'basic', title: 'Basic Text Field', description: 'Standard controlled and uncontrolled single-line input.', platforms: ['web', 'android', 'ios', 'windows', 'macos'] },
    { id: 'search', title: 'Search Input with Clear', description: 'Search input with leading search icon and instant clear button.', platforms: ['web', 'android', 'ios', 'windows', 'macos'] },
    { id: 'password', title: 'Password Entry with Visibility Toggle', description: 'Secure text entry with interactive eye toggle action.', platforms: ['web', 'android', 'ios', 'windows', 'macos'] },
    { id: 'email', title: 'Email Address with Validation', description: 'Email format validation and keyboard auto-complete.', platforms: ['web', 'android', 'ios', 'windows', 'macos'] },
    { id: 'multiline', title: 'Multiline Text Area', description: 'Expandable multi-line text input for long-form comments.', platforms: ['web', 'android', 'ios', 'windows', 'macos'] },
    { id: 'select-autocomplete', title: 'Select Combobox Input', description: 'Drop-down select input with option filter matching.', platforms: ['web'] },
    { id: 'prefix-suffix', title: 'Input with Prefix and Suffix', description: 'Currency or domain adorned text input.', platforms: ['web', 'windows', 'macos'] },
  ],
  bestPractices: {
    do: [
      'Always associate labels with inputs using labelProps / accessibilityLabel',
      'Use secureTextEntry / type="password" for sensitive credentials',
      'Provide clear, non-punitive error messages when validation fails',
      'Configure platform-correct virtual keyboards (e.g. keyboardType="email-address")',
    ],
    dont: [
      'Never rely solely on placeholder text as a substitute for a field label',
      'Never show desktop hover indicators on touch-only mobile devices',
      'Never force web DOM measurement into native TextInput implementations',
    ],
  },
  platforms: {
    web: {
      platform: 'web',
      support: 'native',
      implementation: '@winplaybox/react',
      variants: ['outlined', 'filled', 'standard'],
      recipes: ['basic', 'search', 'password', 'email', 'multiline', 'select-autocomplete', 'prefix-suffix'],
      states: ['default', 'hover', 'focus', 'disabled', 'readonly', 'error', 'success', 'loading'],
      interactions: ['keyboard-typing', 'focus-ring', 'clear-click', 'selection'],
      accessibility: ['aria-invalid', 'aria-describedby', 'aria-required', 'roving-tabIndex'],
      testStatus: 'verified',
    },
    android: {
      platform: 'android',
      support: 'native',
      implementation: '@winplaybox/react-native',
      variants: ['outlined', 'filled'],
      recipes: ['basic', 'search', 'password', 'email', 'multiline'],
      states: ['default', 'focused', 'disabled', 'error'],
      interactions: ['touch-focus', 'soft-keyboard-done', 'clear-tap'],
      accessibility: ['accessibilityRole="none"', 'accessibilityLabel', '48dp touch target'],
      testStatus: 'verified',
    },
    ios: {
      platform: 'ios',
      support: 'native',
      implementation: '@winplaybox/react-native',
      variants: ['default', 'search'],
      recipes: ['basic', 'search', 'password', 'email', 'multiline'],
      states: ['default', 'focused', 'disabled', 'error'],
      interactions: ['touch-focus', 'ios-clear-button-mode', 'secure-entry-toggle'],
      accessibility: ['accessibilityTraits=["none"]', 'VoiceOver value readout', '44pt touch target'],
      testStatus: 'verified',
    },
    windows: {
      platform: 'windows',
      support: 'adapted',
      implementation: '@winplaybox/react-native-windows',
      variants: ['default', 'outlined'],
      recipes: ['basic', 'search', 'password', 'multiline'],
      states: ['default', 'hover', 'focused', 'disabled', 'error'],
      interactions: ['mouse-click', 'keyboard-tab-navigation', 'context-menu-copy-paste'],
      accessibility: ['UIAutomation Text pattern', 'high-contrast-focus-rect'],
      testStatus: 'verified',
    },
    macos: {
      platform: 'macos',
      support: 'adapted',
      implementation: '@winplaybox/react-native-macos',
      variants: ['default'],
      recipes: ['basic', 'search', 'password', 'multiline'],
      states: ['default', 'hover', 'focused', 'disabled', 'error'],
      interactions: ['mouse-click', 'trackpad-selection', 'cmd-shortcuts'],
      accessibility: ['NSAccessibilityTextFieldRole', 'voiceover-announcement'],
      testStatus: 'verified',
    },
  },
};
