import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const tokensSrc = path.resolve(__dirname, '../src');
const distDir = path.resolve(__dirname, '../dist');

// Ensure output directories exist
fs.mkdirSync(path.join(distDir, 'css'), { recursive: true });
fs.mkdirSync(path.join(distDir, 'ts'), { recursive: true });
fs.mkdirSync(path.join(distDir, 'json'), { recursive: true });

function readJson(relPath) {
  const fullPath = path.join(tokensSrc, relPath);
  return JSON.parse(fs.readFileSync(fullPath, 'utf8'));
}

const primitives = readJson('primitives/primitives.tokens.json');
const semantic = readJson('semantic/semantic.tokens.json');
const minimalPack = readJson('packs/minimal.pack.json');
const lightMode = readJson('modes/light.mode.json');
const darkMode = readJson('modes/dark.mode.json');

// Flatten helper
function flattenTokens(obj, prefix = '') {
  let result = {};
  for (const [key, value] of Object.entries(obj)) {
    const newKey = prefix ? `${prefix}-${key}` : key;
    if (value && typeof value === 'object' && !('value' in value)) {
      Object.assign(result, flattenTokens(value, newKey));
    } else if (value && typeof value === 'object' && 'value' in value) {
      result[newKey] = value.value;
      if (newKey.includes('-semantic-')) {
        const shortKey = newKey.replace('-semantic-', '-');
        result[shortKey] = value.value;
      }
    }
  }
  return result;
}

const lightFlat = flattenTokens(lightMode);
const darkFlat = flattenTokens(darkMode);

// Format CSS variable block
function generateCssBlock(selector, flatTokens) {
  const lines = [`${selector} {`];
  for (const [key, val] of Object.entries(flatTokens)) {
    const varName = `--${key}`;
    const spectraVarName = `--spectra-${key}`;
    lines.push(`  ${varName}: ${val};`);
    lines.push(`  ${spectraVarName}: ${val};`);
  }
  lines.push('}\n');
  return lines.join('\n');
}

// Generate CSS (Phase 1: Minimal Flat Style, Light & Dark dynamic modes)
let cssOutput = `/**
 * Spectra UI — Compiled Design Tokens (Phase 1: Minimal Flat Style)
 * Automatically generated by @spectra/tokens build engine. Do not edit manually.
 */\n\n`;

cssOutput += generateCssBlock(':root, [data-pack="minimal"], [data-mode="light"], [data-pack="minimal"][data-mode="light"]', lightFlat);
cssOutput += generateCssBlock('[data-mode="dark"], [data-pack="minimal"][data-mode="dark"]', darkFlat);

fs.writeFileSync(path.join(distDir, 'css/tokens.css'), cssOutput, 'utf8');

// Generate JSON
const jsonOutput = {
  pack: 'minimal',
  modes: {
    light: lightFlat,
    dark: darkFlat,
  },
  primitives,
  semantic,
};
fs.writeFileSync(path.join(distDir, 'json/tokens.json'), JSON.stringify(jsonOutput, null, 2), 'utf8');

// Generate JS (pure ESM JavaScript)
const jsOutput = `/**
 * Spectra UI — Design Tokens JavaScript Exports
 */

export const tokens = ${JSON.stringify(jsonOutput, null, 2)};

export const lightTokens = ${JSON.stringify(lightFlat, null, 2)};
export const darkTokens = ${JSON.stringify(darkFlat, null, 2)};

export function getTokens(mode = 'light') {
  return mode === 'dark' ? darkTokens : lightTokens;
}
`;
fs.writeFileSync(path.join(distDir, 'ts/tokens.js'), jsOutput, 'utf8');

// Also write TypeScript source
const tsOutput = `/**
 * Spectra UI — Design Tokens TypeScript Exports
 */

export const tokens = ${JSON.stringify(jsonOutput, null, 2)} as const;

export const lightTokens = ${JSON.stringify(lightFlat, null, 2)} as const;
export const darkTokens = ${JSON.stringify(darkFlat, null, 2)} as const;

export type TokenKey = keyof typeof lightTokens;
export type ColorScheme = 'light' | 'dark';
export type StylePack = 'minimal';

export function getTokens(mode: ColorScheme = 'light') {
  return mode === 'dark' ? darkTokens : lightTokens;
}
`;
fs.writeFileSync(path.join(distDir, 'ts/tokens.ts'), tsOutput, 'utf8');

const indexJs = `export * from './tokens.js';\n`;
fs.writeFileSync(path.join(distDir, 'ts/index.js'), indexJs, 'utf8');

const indexTs = `export * from './tokens';\n`;
fs.writeFileSync(path.join(distDir, 'ts/index.ts'), indexTs, 'utf8');

const dtsOutput = `export type TokenKey = string;
export type ColorScheme = 'light' | 'dark';
export type StylePack = 'minimal';

export declare const tokens: {
  pack: 'minimal';
  modes: {
    light: Record<string, string>;
    dark: Record<string, string>;
  };
};

export declare const lightTokens: Record<string, string>;
export declare const darkTokens: Record<string, string>;

export declare function getTokens(mode?: ColorScheme): Record<string, string>;
`;
fs.writeFileSync(path.join(distDir, 'ts/tokens.d.ts'), dtsOutput, 'utf8');
fs.writeFileSync(path.join(distDir, 'ts/index.d.ts'), dtsOutput, 'utf8');

console.log('✅ Tokens compiled successfully to dist/css, dist/ts, and dist/json');
